---
title: "In class ex 7"
author: "Dhreeti"
---

1. Getting Started 

```{r}
pacman::p_load(tidyverse, tsibble, feasts, fable, seasonal)
```

2. Load data

```{r}
ts_data <- read_csv(
  "data/visitor_arrivals_by_air.csv")
```

```{r}
ts_data$`Month-Year` <- dmy(
  ts_data$`Month-Year`)
```





```{r}
ts_data
```

```{r}
ts_data_ts <- ts(ts_data)       
head(ts_data_ts)
```


```{r}
ts_tsibble <- ts_data %>%
  mutate(Month = yearmonth(`Month-Year`)) %>%
  as_tsibble(index = `Month`)
```



```{r}
ts_tsibble
```
```{r}
ts_longer <- ts_data %>%
  pivot_longer(cols = c(2:34),
               names_to = "Country",
               values_to = "Arrivals")
```

 Visualising single time-series: ggplot2 methods

```{r}
ts_longer %>%
  filter(Country == "Vietnam") %>%
  ggplot(aes(x = `Month-Year`, 
             y = Arrivals))+
  geom_line(size = 0.5)
```



Plotting multiple time-series data with ggplot2 methods


```{r}
ggplot(data = ts_longer, 
       aes(x = `Month-Year`, 
           y = Arrivals,
           color = Country))+
  geom_line(size = 0.5) +
  theme(legend.position = "bottom", 
        legend.box.spacing = unit(0.5, "cm"))
```



```{r}

#| echo : false
#| fig-height :30
ggplot(data = ts_longer, 
       aes(x = `Month-Year`, 
           y = Arrivals))+
  geom_line(size = 0.5) +
  facet_wrap(~ Country,
             ncol = 6,
             scales = "free_y") +
  theme_bw()
```


Visual Analysis of Time-series Data


```{r}
tsibble_longer <- ts_tsibble %>%
  pivot_longer(cols = c(2:34),
               names_to = "Country",
               values_to = "Arrivals")
```




```{r}
tsibble_longer %>%
  filter(Country == "Vietnam" |
         Country == "Italy") %>% 
  autoplot(Arrivals) + 
  facet_grid(Country ~ ., scales = "free_y")
```

```{r}
tsibble_longer %>%
  filter(Country == "Vietnam" |
         Country == "Italy") %>% 
  gg_subseries(Arrivals)
```
```{r}
tsibble_longer %>%
  filter(`Country` == "Vietnam" |
         `Country` == "Italy" |
         `Country` == "United Kingdom" |
         `Country` == "China") %>%
  PACF(Arrivals) %>%
  autoplot()
```
```{r}
tsibble_longer %>%
  filter(`Country` == "Vietnam") %>%
  gg_tsdisplay(Arrivals)
```

