---
title: "In class exercise 5"
author: "Dhreeti"
---

---
title: "In class exercise 5"
author: "Dhreeti"
execute: 
  eval: true
  warning: false
---

Getting Started

```{r}
pacman::p_load(tidyverse,readxl,easystats,gtsummary, SmartEDA, ggstatsplot)
```

Importing data 

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls")

```


Data Overview


```{r}
car_resale %>%
  ExpData(type = 2)


```



```{r}
list(car_resale)



```




```{r}

cols <-c("Mfg_Month","HP_Bin","CC_bin","Doors","Gears","Cylinders","Fuel_Type", "Color","Met_Color", "Automatic","Mfr_Guarantee","Bovag_Guarantee",
         "ABS", "Airbabg_1","Airbabg_2","Airco","Automatic_airco","Boardcomputer","CD_Player","Central_Lock","Powered_windows", "Powered_Steering","Radio","Mistlamps","Sport_Model","Backseat_Divider","Metallic_Rim","Radio_cassette","Tow_Bar")



```



```{r}

car_resale %>% 
  ExpNumViz((target = NULL),
            nlim = 10,
            Page = c(2,2))

```


```{r}

car_resale %>% 
  ExpNumViz((target = "Price"),
            nlim = 10,
            Page = c(2,2),
            theme= "Default")
```



```{r}
#| fig-width: 12
#| fig-height: 10

car_resale %>% 
  ExpCatViz(target = NULL,
            col ="sky blue",
            clim = 10,
            margin = 2,
            Page = c(4,4),
            sample = 16)

```



```{r}

model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period, data = car_resale)
check_collinearity(model)



```

```{r}

check_c <- check_collinearity(model)
plot(check_c)

```


```{r}
model1 <- lm(Price ~ Age_08_04  + KM + Weight + Guarantee_Period, data = car_resale)

check_normality(model1)

```
```{r}

summary(model1)
```

```{r}
tbl_regression(model1, 
               intercept = TRUE) %>%

add_glance_source_note(
  label = list(sigma ~ "\U03C3"),
  include = c(r.squared,adj.r.squared,AIC,statistic,p.value,sigma))
```

```{r}
p_model1 <- parameters(model1)
```

```{r}
plot(parameters(model1))
```
```{r}
ggcoefstats(model1,output = "plot")
```


